// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NikSchaefer/go-fiber/ent/otp"
	"github.com/NikSchaefer/go-fiber/ent/predicate"
	"github.com/NikSchaefer/go-fiber/ent/user"
)

// OTPUpdate is the builder for updating OTP entities.
type OTPUpdate struct {
	config
	hooks    []Hook
	mutation *OTPMutation
}

// Where appends a list predicates to the OTPUpdate builder.
func (_u *OTPUpdate) Where(ps ...predicate.OTP) *OTPUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OTPUpdate) SetUpdatedAt(v time.Time) *OTPUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetType sets the "type" field.
func (_u *OTPUpdate) SetType(v otp.Type) *OTPUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *OTPUpdate) SetNillableType(v *otp.Type) *OTPUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetUsed sets the "used" field.
func (_u *OTPUpdate) SetUsed(v bool) *OTPUpdate {
	_u.mutation.SetUsed(v)
	return _u
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_u *OTPUpdate) SetNillableUsed(v *bool) *OTPUpdate {
	if v != nil {
		_u.SetUsed(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *OTPUpdate) SetUserID(id int) *OTPUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OTPUpdate) SetUser(v *User) *OTPUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OTPMutation object of the builder.
func (_u *OTPUpdate) Mutation() *OTPMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OTPUpdate) ClearUser() *OTPUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OTPUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OTPUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OTPUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OTPUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OTPUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := otp.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OTPUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := otp.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "OTP.type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OTP.user"`)
	}
	return nil
}

func (_u *OTPUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(otp.Table, otp.Columns, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(otp.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(otp.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Used(); ok {
		_spec.SetField(otp.FieldUsed, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UserTable,
			Columns: []string{otp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UserTable,
			Columns: []string{otp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OTPUpdateOne is the builder for updating a single OTP entity.
type OTPUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OTPMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OTPUpdateOne) SetUpdatedAt(v time.Time) *OTPUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetType sets the "type" field.
func (_u *OTPUpdateOne) SetType(v otp.Type) *OTPUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *OTPUpdateOne) SetNillableType(v *otp.Type) *OTPUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetUsed sets the "used" field.
func (_u *OTPUpdateOne) SetUsed(v bool) *OTPUpdateOne {
	_u.mutation.SetUsed(v)
	return _u
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_u *OTPUpdateOne) SetNillableUsed(v *bool) *OTPUpdateOne {
	if v != nil {
		_u.SetUsed(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *OTPUpdateOne) SetUserID(id int) *OTPUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OTPUpdateOne) SetUser(v *User) *OTPUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OTPMutation object of the builder.
func (_u *OTPUpdateOne) Mutation() *OTPMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OTPUpdateOne) ClearUser() *OTPUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the OTPUpdate builder.
func (_u *OTPUpdateOne) Where(ps ...predicate.OTP) *OTPUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OTPUpdateOne) Select(field string, fields ...string) *OTPUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OTP entity.
func (_u *OTPUpdateOne) Save(ctx context.Context) (*OTP, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OTPUpdateOne) SaveX(ctx context.Context) *OTP {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OTPUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OTPUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OTPUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := otp.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OTPUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := otp.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "OTP.type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OTP.user"`)
	}
	return nil
}

func (_u *OTPUpdateOne) sqlSave(ctx context.Context) (_node *OTP, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(otp.Table, otp.Columns, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OTP.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, otp.FieldID)
		for _, f := range fields {
			if !otp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != otp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(otp.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(otp.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Used(); ok {
		_spec.SetField(otp.FieldUsed, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UserTable,
			Columns: []string{otp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UserTable,
			Columns: []string{otp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OTP{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
