// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NikSchaefer/go-fiber/ent/otp"
	"github.com/NikSchaefer/go-fiber/ent/user"
	"github.com/google/uuid"
)

// OTPCreate is the builder for creating a OTP entity.
type OTPCreate struct {
	config
	mutation *OTPMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OTPCreate) SetCreatedAt(v time.Time) *OTPCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OTPCreate) SetNillableCreatedAt(v *time.Time) *OTPCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OTPCreate) SetUpdatedAt(v time.Time) *OTPCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OTPCreate) SetNillableUpdatedAt(v *time.Time) *OTPCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *OTPCreate) SetCode(v string) *OTPCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *OTPCreate) SetNillableCode(v *string) *OTPCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *OTPCreate) SetType(v otp.Type) *OTPCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *OTPCreate) SetNillableType(v *otp.Type) *OTPCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetUsed sets the "used" field.
func (_c *OTPCreate) SetUsed(v bool) *OTPCreate {
	_c.mutation.SetUsed(v)
	return _c
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_c *OTPCreate) SetNillableUsed(v *bool) *OTPCreate {
	if v != nil {
		_c.SetUsed(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OTPCreate) SetExpiresAt(v time.Time) *OTPCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *OTPCreate) SetNillableExpiresAt(v *time.Time) *OTPCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OTPCreate) SetID(v uuid.UUID) *OTPCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OTPCreate) SetNillableID(v *uuid.UUID) *OTPCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *OTPCreate) SetUserID(id uuid.UUID) *OTPCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OTPCreate) SetUser(v *User) *OTPCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the OTPMutation object of the builder.
func (_c *OTPCreate) Mutation() *OTPMutation {
	return _c.mutation
}

// Save creates the OTP in the database.
func (_c *OTPCreate) Save(ctx context.Context) (*OTP, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OTPCreate) SaveX(ctx context.Context) *OTP {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OTPCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OTPCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OTPCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := otp.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := otp.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Code(); !ok {
		v := otp.DefaultCode()
		_c.mutation.SetCode(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := otp.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Used(); !ok {
		v := otp.DefaultUsed
		_c.mutation.SetUsed(v)
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		v := otp.DefaultExpiresAt()
		_c.mutation.SetExpiresAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := otp.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OTPCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OTP.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OTP.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "OTP.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := otp.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OTP.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "OTP.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := otp.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "OTP.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Used(); !ok {
		return &ValidationError{Name: "used", err: errors.New(`ent: missing required field "OTP.used"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OTP.expires_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OTP.user"`)}
	}
	return nil
}

func (_c *OTPCreate) sqlSave(ctx context.Context) (*OTP, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OTPCreate) createSpec() (*OTP, *sqlgraph.CreateSpec) {
	var (
		_node = &OTP{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(otp.Table, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(otp.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(otp.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(otp.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(otp.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Used(); ok {
		_spec.SetField(otp.FieldUsed, field.TypeBool, value)
		_node.Used = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(otp.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UserTable,
			Columns: []string{otp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_otps = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OTPCreateBulk is the builder for creating many OTP entities in bulk.
type OTPCreateBulk struct {
	config
	err      error
	builders []*OTPCreate
}

// Save creates the OTP entities in the database.
func (_c *OTPCreateBulk) Save(ctx context.Context) ([]*OTP, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OTP, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OTPMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OTPCreateBulk) SaveX(ctx context.Context) []*OTP {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OTPCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OTPCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
