// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// OTP is the predicate function for otp builders.
type OTP func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
